server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.98.210.67:3306/study?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: '!Dkj19930704'
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 47.98.210.67
    port: 6379
    password: dkj64048231
    timeout: 10000ms
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: -1ms
        max-active: 8

logging:
  config: classpath:log4j2.yml

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

#    #druid相关配置
#    druid:
#      #监控统计拦截的filters
#      filters: stat
#      driver-class-name: com.mysql.jdbc.Driver
#      #基本属性
#      url: jdbc:mysql://47.98.210.67:3306/study?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
#      username: root
#      password: !Dkj19930704
#      #配置初始化大小/最小/最大
#      initial-size: 1
#      min-idle: 1
#      max-active: 20
#      #获取连接等待超时时间
#      max-wait: 60000
#      #间隔多久进行一次检测，检测需要关闭的空闲连接
#      time-between-eviction-runs-millis: 60000
#      #一个连接在池中最小生存的时间
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 'x'
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
#      pool-prepared-statements: false
#      max-pool-prepared-statement-per-connection-size: 20